###Получим всех содрудников
GET http://localhost:8080/employees
###Создать содрудника
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Test",
  "departament": 1,
  "salary": 80000

}
###Создать содрудника2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Testos",
  "lastName": "Testos",
  "departament": 1,
  "salary": 20000

}
###Создать содрудника3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Testik",
  "lastName": "Testik",
  "departament": 2,
  "salary": 50000

}

###Создать содрудника4
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Testikq",
  "lastName": "Testiwk",
  "departament": 2,
  "salary": 70000

}
###Создать содрудника5
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Tesqtik",
  "lastName": "Testwik",
  "departament": 1,
  "salary": 55000

}
###Создать содрудника6
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Testtik",
  "lastName": "Testtik",
  "departament": 1,
  "salary": 70000

}
###Сумма Затрат
GET http://localhost:8080/employees/salary/sum

### Миниимальная зарплата
GET http://localhost:8080/employees/min/salary

### Максимальная зарплата
GET http://localhost:8080/employees/max/salary

###Среденяя зарплата
GET http://localhost:8080/employees/highSalary
